apiVersion: v1
kind: Pod
metadata:
  name: myrpc
  labels:
    app: gprc-server
spec:
  containers:
    - name: myrpc
      image: myrpc
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 2408
          protocol: TCP
