# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello-world.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hello-world.proto',
  package='myservice',
  syntax='proto3',
  serialized_options=b'Z8github.com/prateek2408/BookExamples/gRPC/proto/myservice',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11hello-world.proto\x12\tmyservice\"\t\n\x07Request\"\x1e\n\rStringMessage\x12\r\n\x05reply\x18\x01 \x01(\t2E\n\tMyService\x12\x38\n\x06MyFunc\x12\x12.myservice.Request\x1a\x18.myservice.StringMessage\"\x00\x42:Z8github.com/prateek2408/BookExamples/gRPC/proto/myserviceb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='myservice.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=41,
)


_STRINGMESSAGE = _descriptor.Descriptor(
  name='StringMessage',
  full_name='myservice.StringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='myservice.StringMessage.reply', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['StringMessage'] = _STRINGMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:myservice.Request)
  })
_sym_db.RegisterMessage(Request)

StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), {
  'DESCRIPTOR' : _STRINGMESSAGE,
  '__module__' : 'hello_world_pb2'
  # @@protoc_insertion_point(class_scope:myservice.StringMessage)
  })
_sym_db.RegisterMessage(StringMessage)


DESCRIPTOR._options = None

_MYSERVICE = _descriptor.ServiceDescriptor(
  name='MyService',
  full_name='myservice.MyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=75,
  serialized_end=144,
  methods=[
  _descriptor.MethodDescriptor(
    name='MyFunc',
    full_name='myservice.MyService.MyFunc',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_STRINGMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYSERVICE)

DESCRIPTOR.services_by_name['MyService'] = _MYSERVICE

# @@protoc_insertion_point(module_scope)
